<?php

use App\Http\Controllers\admin\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\admin\BrandController;
use App\Http\Controllers\admin\BrandmodelController;
use App\Http\Controllers\admin\MaintenanceschedulesController;
use App\Http\Controllers\admin\MaintenancesController;
use App\Http\Controllers\admin\OcuppantsController;
use App\Http\Controllers\admin\ProgrammingmassiveController;
use App\Http\Controllers\admin\ProgrammingsController;
use App\Http\Controllers\admin\RouteController;
use App\Http\Controllers\admin\RoutepathController;
use App\Http\Controllers\admin\RoutezoneController;
use App\Http\Controllers\admin\SchedulesController;
use App\Http\Controllers\admin\SchedulesdatesController;
use App\Http\Controllers\admin\SectorController;
use App\Http\Controllers\admin\UserController;
use App\Http\Controllers\admin\UsertypeController;
use App\Http\Controllers\admin\VehiclecolorController;
use App\Http\Controllers\admin\VehicleController;
use App\Http\Controllers\admin\VehicleimagesController;
use App\Http\Controllers\admin\VehicleocuppantsController;
use App\Http\Controllers\admin\VehiclerouteController;
use App\Http\Controllers\admin\VehicletypeController;
use App\Http\Controllers\admin\ZoneController;
use App\Http\Controllers\admin\ZonecoordController;

Route::get('/', [AdminController::class, 'index'])->name('home')->middleware('checkAdmin');
Route::resource('brands', BrandController::class)->names('admin.brands')->middleware('checkAdmin');
Route::resource('models', BrandmodelController::class)->names('admin.models')->middleware('checkAdmin');
Route::resource('vehicles', VehicleController::class)->names('admin.vehicles')->middleware('checkAdmin');
Route::resource('vehicleimages', VehicleimagesController::class)->names('admin.vehicleimages')->middleware('checkAdmin');
Route::get('modelsbybrand/{id}', [BrandmodelController::class, 'modelsbybrand'])->name('admin.modelsbybrand')->middleware('checkAdmin');
Route::get('imageprofile/{id}/{vehicle_id}', [VehicleimagesController::class, 'profile'])->name('admin.imageprofile')->middleware('checkAdmin');
Route::resource('zones', ZoneController::class)->names('admin.zones')->middleware('checkAdmin');
Route::resource('zonecoords', ZonecoordController::class)->names('admin.zonecoords')->middleware('checkAdmin');
Route::resource('sectors', SectorController::class)->names('admin.sectors')->middleware('checkAdmin');
Route::resource('types', VehicletypeController::class)->names('admin.types')->middleware('checkAdmin');
Route::resource('colors', VehiclecolorController::class)->names('admin.colors')->middleware('checkAdmin');
Route::resource('usertypes', UsertypeController::class)->names('admin.usertypes')->middleware('checkAdmin');
Route::resource('users', UserController::class)->names('admin.users')->middleware('checkAdmin');
Route::resource('schedules', SchedulesController::class)->names('admin.schedules')->middleware('checkAdmin');
Route::get('vehicles/{id}/images', [VehicleController::class, 'showImages'])->name('vehicles.images')->middleware('checkAdmin');
Route::resource('vehicleocuppants', VehicleocuppantsController::class)->names('admin.vehicleocuppants')->middleware('checkAdmin');
Route::get('searchbydni/{id}', [VehicleocuppantsController::class, 'searchbydni'])->name('admin.searchbydni')->middleware('checkAdmin');
Route::post('vehicleocuppants/confirm', [VehicleocuppantsController::class, 'confirm'])->name('admin.vehicleocuppants.confirm')->middleware('checkAdmin');
Route::resource('ocuppants', OcuppantsController::class)->names('admin.ocuppants')->middleware('checkAdmin');
Route::resource('maintenances', MaintenancesController::class)->names('admin.maintenances')->middleware('checkAdmin');
Route::resource('maintenanceschedules', MaintenanceschedulesController::class)->names('admin.maintenanceschedules')->middleware('checkAdmin');
Route::resource('schedulesdates', SchedulesdatesController::class)->names('admin.schedulesdates')->middleware('checkAdmin');
Route::resource('routes', RouteController::class)->names('admin.routes')->middleware('checkAdmin');
Route::resource('routezones', RoutezoneController::class)->names('admin.routezones')->middleware('checkAdmin');
Route::resource('vehicleroutes', VehiclerouteController::class)->names('admin.vehicleroutes')->middleware('checkAdmin');
Route::get('maintenanceschedules/ocuppantsbyvehicle/{vehicle_id}', [MaintenanceschedulesController::class, 'ocuppantsByVehicle'])->name('admin.ocuppantsbyvehicle')->middleware('checkAdmin');
Route::get('routes/showeditcoordinatesform/{route_id}/{type}', [RouteController::class, 'showEditCoordinatesForm'])->name('admin.showeditcoordinatesform')->middleware('checkAdmin');
Route::post('routes/updateroutestartandendcoords', [RouteController::class, 'updateRouteStartAndEndCoords'])->name('admin.updateroutestartandendcoords')->middleware('checkAdmin');
Route::resource('programming', ProgrammingsController::class)->names('admin.programming')->middleware('checkAdmin');
Route::get('searchprogramming', [ProgrammingsController::class, 'searchprogramming'])->name('admin.searchprogramming')->middleware('checkAdmin');
Route::post('programming/storeWeekdays', [ProgrammingsController::class, 'storeWeekdaysProgramming'])->name('admin.programming.storeWeekdays')->middleware('checkAdmin');
Route::post('programming/storeInterleaved', [ProgrammingsController::class, 'storeInterleavedProgramming'])->name('admin.programming.storeInterleaved')->middleware('checkAdmin');
Route::get('routes/showroutemap/{route_id}', [RouteController::class, 'showRouteMap'])->name('admin.showroutemap')->middleware('checkAdmin');
Route::resource('routepaths', RoutepathController::class)->names('admin.routepaths')->middleware('checkAdmin');
Route::resource('programmingmassive', ProgrammingmassiveController::class)->names('admin.programmingmassive')->middleware('checkAdmin');